# Configuraci칩n est치tica de Traefik
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true # Habilita el dashboard de Traefik (solo para desarrollo)

providers:
  docker:
    exposedByDefault: false # No exponer contenedores autom치ticamente por seguridad
  file:
    directory: /etc/traefik/dynamic_config/
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: ${LETSENCRYPT_EMAIL} # Set directly for testing
      storage: /letsencrypt/acme.json
      # Usamos tlsChallenge para la validaci칩n con Let's Encrypt
      tlsChallenge: {}